env:
language: java
before_install:
  - "./gradlew -version"
install: "./gradlew assemble"
script: "./gradlew clean fastbuild"
jdk:
  - oraclejdk7
  - oraclejdk8
after_success:
  - "./gradlew bundle"
deploy:
  provider: releases
  user: "ikescorp"
  password: "ikescorp0"
  file: "zips/dbfit-complete-3.1.0.zip"
  skip_cleanup: true
  on:
    tags: truee
# the next line is a workaround for https://github.com/travis-ci/travis-artifacts/issues/23
#  - "gem install --version 0.8.9 faraday"
#  - "gem install travis-artifacts"
#  - "travis-artifacts upload --path zips --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID"
